version: '2'

volumes:
  postgres-shared:

services:
  postgres-shared:
    image: postgres:15
    expose:
      - "5432"
    ports:
      - "5436:5432"
    volumes:
      - postgres-shared:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
